version: '2'

services:
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:ubuntu-5.0.1
    user: root
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - 10050:10050
      - 10051:10051
    environment:
      - ZBX_HOSTNAME=192.168.226.129
      - ZBX_SERVER_HOST=192.168.226.129
